MONTHLY_PERIOD_SENTINEL = -1
DEFAULT_CURRENCIES = ("RUB", "USD", "TRY", "EUR")
DATE_INPUT_FORMAT = "%d.%m.%Y"

PAYMENT_MODE_SPLIT = "split"
PAYMENT_MODE_FIXED = "fixed"
PAYMENT_MODES = (PAYMENT_MODE_SPLIT, PAYMENT_MODE_FIXED)
